### ISSUE TITLE
24th line throws exception

### ISSUE THREAD

**Issue by Caponezed** [VDWWD/epplus-export-list-t-to-excel#1]
https://github.com/VDWWD/epplus-export-list-t-to-excel/blame/e698b59425ec4bbd0ce4fee26c44d16327b960ab/EPPlus.cs#L24

**Comment by Caponezed** [comment]
but thanks for the method. It really helped me

**Comment by VDWWD** [comment]
Which version of EPPlus are you using? This project was made a while ago and somewhere in a later update, EPPlus moved from using the Excel format of an array starting at 1 to the arrays used in programming that start at 0.  I suspect this is the issue. I will test with a newer version of EPPlus and post an update if needed.

I tested the code with the old version 4.5.3.3 and it works fine.

**Comment by Caponezed** [comment]
Yes, it is fixed by changing the index from 1 to 0. Works fine 👍 

I am not at the computer right now, don't remember the version
